### ISSUE TITLE
[Feature request] Generate multiple things at once

### ISSUE THREAD

**Issue by p32929** [tsedio/tsed-cli#201]
First of all, I wanna thank you guys for creating and maintaining tsed. 

When we try to generate something using `tsed g`, it only allows us to generate one thing at a time.
![Screenshot (151)](https://user-images.githubusercontent.com/6418354/151536413-e1220fb2-7590-4bba-a4ad-f6f1102c0297.png)

it would've been even more awesome, if we could generate multiple things at once like the screenshot below using the `tsed g` command:
![Screenshot (152)](https://user-images.githubusercontent.com/6418354/151536599-9785f602-a1e1-4eac-b431-31b3d930e47a.png)

Thanks a million

**Comment by VincentThomas06** [comment]
+1 that would be nice!

**Comment by Romakita** [comment]
PR is welcome ;)
