### ISSUE TITLE
Unable to find module '../envs' in a new project

### ISSUE THREAD

**Issue by yaodong** [tsedio/tsed-cli#217]
I can't run a brand new project created by `tsed-cli`. The error message is:

```
[ERROR] 17:34:59 Error: Cannot find module '../envs'
Require stack:
- /Users/xxx/project/abc/src/config/logger/index.ts
- /Users/xxx/project/abc/src/config/index.ts
- /Users/xxx/project/abc/src/Server.ts
- /Users/xxx/project/abc/src/index.ts
```

So I checked file `src/config/logger/index.ts`. I see it imports an non-exist module

```
import {isProduction} from "../envs";
```

Probably it's a typo because I see there is a file `src/config/env/index.js` which contains constant `isProduction`.

Additionally, module `envs` is used by `src/index.ts` but it is not imported.

Please let me know if this bug report makes sense. Happy to create a PR if needed.

**Comment by Romakita** [comment]
Thanks for your feedback, I published a new CLI version, but I forgot some changes. I'll fix that immediately.
