### ISSUE TITLE
[BUG] Receipe resolve imports Receipe service that doesn't exist

### ISSUE THREAD

**Issue by fredlemieux** [tsedio/tsed-cli#258]
## Information
- **Version:3.21.3
- Mac M1

After running the `tsed init` with the feature `TypeGraphQL`, the install works, however there is a missing service:

In the file `src/resolvers/recipes/RecipeResolver.ts` there is an import of a `"../../services/RecipeService` that doesn't exist.  
```
import {ResolverService} from "@tsed/typegraphql";
import {Arg, Query} from "type-graphql";
import {RecipeService} from "../../services/RecipeService";
import {Recipe} from "./Recipe";
import {RecipeNotFoundError} from "./RecipeNotFoundError";

@ResolverService(Recipe)
export class RecipeResolver {
  constructor(private recipeService: RecipeService) {}

  @Query((returns) => Recipe)
  async recipe(@Arg("id") id: string) {
    const recipe = await this.recipeService.findById(id);

    if (recipe === undefined) {
      throw new RecipeNotFoundError(id);
    }

    return recipe;
  }

  @Query((returns) => [Recipe], {description: "Get all the recipes from around the world "})
  async recipes(): Promise<Recipe[]> {
    return this.recipeService.findAll({});
  }
}

```

## Example

```ts

```

## Acceptance criteria

- [ ] No typescript error
- [ ] yarn start, results in working app

**Comment by Romakita** [comment]
I'm not able to reproduce. I think, you haven't remove all file before running `tsed init .`.

For me, the file is correctly generated with the next release :)

**Comment by fredlemieux** [comment]
Sorry for the delay, been a busy few days.  Okay, so I've tried a fresh install of the tsed/cli on my Linux PC (just in case the issue is platform specific), and the issue is still there.  Here is a screen shot of the files and the error in VSCode:

![ReceipeService](https://user-images.githubusercontent.com/7422952/177406412-371690ae-e83d-4089-8587-8b21aac816f6.png)

**Comment by fredlemieux** [comment]
I've searched the codebase and there is only [one reference I](https://github.com/tsedio/tsed-cli/blob/ec43a5ae7815fc0c9454558a5b4a1a9f0cee87dc/packages/cli-plugin-typegraphql/templates/init/src/resolvers/recipes/RecipeResolver.ts) can find to Recipe Service

**Comment by Romakita** [comment]
I also tested on mac with the latest version and it’s works. I’m not able to reproduce.

**Comment by fredlemieux** [comment]
Okay, I've just created a service and model myself and I'm getting the hang of this (I'm new to prisma too!)... I might be able to look into creating a PR to get the cli to do what I'm thinking, but just in case I'm missing something.... Am I supposed to do anything after running `tsed init .` or should it all work? Do I need to run yarn `prisma:generate`?

Could you share your folder structure?  Because I definitely have no src/services/RecipeService in my folder directory and that's multiple attempts on two separate PCs and OSs tried.

**Comment by Romakita** [comment]
Got it. Sorry, I totally missed that. I see where the problem about RecipeService now.

Yes you have create a model in the schema and run `yarn prisma:generate` after the cli installation is done. 
Start the tuto at this step: https://tsed.io/tutorials/prisma.html#prisma-client-configuration

**Comment by Romakita** [comment]
```typescript
import {Injectable} from "@tsed/di";
import {Recipe} from "../resolvers";

@Injectable()
export class RecipeService {
  async findById(id: string) {
    return new Recipe({id})
  }
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  async findAll(query: any) {
    return []
  }
}

```

**Comment by Romakita** [comment]
Solved :)
Release is on going ;)
