### ISSUE TITLE
[BUG] init including oidc imports wrong version

### ISSUE THREAD

**Issue by TomsOverBaghdad** [tsedio/tsed-cli#302]
## Information

- **Version:** 4.2.6
- Packages: oicd-provider

Initializing a project and including open id connect provider installs oicd-provider version 8.0.0 which is incompatible with the node version set. The error says I need to use node version 18 but when upgrading node to 18 the packages all install correctly however I get errors in that package when trying to `yarn start`. Errors that are in my node modules folder, and out of my control, because the new version is a breaking version for this project.

After some digging in the code I found the oicd-provider is set to [^7.11.1 in the tsed repo](https://github.com/tsedio/tsed/blob/86374ccf51b7710f296bd3026fcdce5d645039f4/packages/security/oidc-provider/package.json#L50) but looking for the `"latest"` in [here](https://github.com/tsedio/tsed-cli/blob/ec43a5ae7815fc0c9454558a5b4a1a9f0cee87dc/packages/cli-plugin-oidc-provider/src/CliPluginOidcProviderModule.ts#L15)

forcing the "oidc-provider": "^7.11.1", and "@types/oidc-provider": "^7.11.1", in my yarn file fixed this.

I believe setting the version instead of using latest in [CliPluginOidcProviderModule.js](https://github.com/tsedio/tsed-cli/blob/ec43a5ae7815fc0c9454558a5b4a1a9f0cee87dc/packages/cli-plugin-oidc-provider/src/CliPluginOidcProviderModule.ts#L15) will help. I can open up a PR but wasn't sure how you wanted to handle this considering that upgrading 

## Example

```bash
yarn install -g @tsed/cli
tsed init .
```
cli inputs
```
? Choose the target platform: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project Database, Passport.js, Swagger, OpenID Connect provider, Linter, 
Bundler
? Choose a ORM manager Mongoose
? Choose linter tools framework EsLint
? Choose extra linter tools Prettier, Lint on commit
? Choose your bundler Babel
? Choose the OIDC base path server /oidc
? Choose the package manager: Yarn
```
yarn 
```
  ❯ Install
    ✔ Write package.json
    ✔ Installing dependencies using Yarn
    ✖ Command failed with exit code 1: yarn add @react-native-community/masked-view@^0.1.11 @react-navigation/bot…
      error oidc-provider@8.0.0: The engine "node" is incompatible with this module. Expected version "18". Got "…
      error Found incompatible module.
      yarn add v1.22.19
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    ◼ Add devDependencies using Yarn
    ◼ Clean
Error: Command failed with exit code 1: yarn add @react-native-community/masked-view@^0.1.11 @react-navigation/bottom-tabs@^5.11.15 @react-navigation/native@^5.9.8 @reduxjs/toolkit@^1.7.1 @tsed/ajv@^7.8.2 @tsed/common@^7.8.2 @tsed/core@^7.8.2 @tsed/di@^7.8.2 @tsed/engines@^7.8.2 @tsed/exceptions@^7.8.2 @tsed/json-mapper@^7.8.2 @tsed/logger@^6.3.3 @tsed/logger-file@^6.3.3 @tsed/openspec@^7.8.2 @tsed/platform-cache@^7.8.2 @tsed/platform-exceptions@^7.8.2 @tsed/platform-express@^7.8.2 @tsed/platform-log-middleware@^7.8.2 @tsed/platform-middlewares@^7.8.2 @tsed/platform-params@^7.8.2 @tsed/platform-response-filter@^7.8.2 @tsed/platform-views@^7.8.2 @tsed/schema@^7.8.2 @tsed/swagger@^7.8.2 ajv@^8.11.2 barrelsby@^2.5.1 body-parser@^1.20.1 compression@^1.7.4 cookie-parser@^1.4.6 cors@^2.8.5 cross-env@^7.0.3 dotenv@^16.0.3 dotenv-expand@^9.0.0 dotenv-flow@^3.2.0 expo@~44.0.0 expo-status-bar@~1.2.0 express@^4.18.2 method-override@^3.0.0 native-base@^3.3.7 react-native-animated-nav-tab-bar@^3.1.7 react-native-gesture-handler@~2.1.0 react-native-reanimated@~2.3.1 react-native-screens@~3.10.1 react-redux@^7.2.6 @tsed/passport@^7.8.2 passport oidc-provider @tsed/oidc-provider @tsed/jwks @tsed/adapters bcrypt @tsed/mongoose@^7.8.2 mongoose
error oidc-provider@8.0.0: The engine "node" is incompatible with this module. Expected version "18". Got "16.15.1"
error Found incompatible module.
```

## Acceptance criteria

- [ ] Setting the oicd-provider version to 7.11.1 or some other solution that's more stable (upgrading oicd-provider would mean also upgrading here which would be an easy miss and cause this bug to continue)

**Comment by Romakita** [comment]
Hello @TomsOverBaghdad 
In general I let latest flag to simplify installation. In most case it works, because maintaining each dependencies up to date is a pain point.
Right know, you can fix the version in the cli until the problem isn’t solved :)
Thanks for your help ;)

romain

**Comment by Romakita** [comment]
Note: the author of oidc-provider exaggerates to fix such recent versions... ^^

**Comment by TomsOverBaghdad** [comment]
Thanks for the quick reply!

Do we need to have "oidc-provider" here when we have the dependency already in "tsed/oidc-provider"? Could a solution be to change the `peerDependency` [in tsed](https://github.com/tsedio/tsed/blob/86374ccf51b7710f296bd3026fcdce5d645039f4/packages/security/oidc-provider/package.json#L54) to be "7.11.1" and then remove the "oidc-provider" in this repo?

**Comment by Romakita** [comment]
The CLI must be fixed, because peerDependency is resolved differently depending on the used packageManager. And the problem is temporary, until I haven't investigued on the OIDC v8 issue

**Comment by Romakita** [comment]
U
