### ISSUE TITLE
You must provide a `choices` parameter

### ISSUE THREAD

**Issue by M1000fr** [tsedio/tsed-cli#359]
## Information

- **Node Version:** 18.19.0
- **TSED CLI Version:** 5.0.0

Get this error when i want to init a project with command `tsed init .`

![alt text](https://s3.m1000.fr/sharex/2024/01/WindowsTerminal_pTx2XUC3fw.png)

**Comment by Romakita** [comment]
Noted. I’ll fix that tomorrow.
Meanwhile, You can install a project by using the @tsed/cli@v4 @M1000fr 

see you!

**Comment by Romakita** [comment]
Release is on going ^^
