### ISSUE TITLE
New project - package.json - lint options cause tests to fail

### ISSUE THREAD

**Issue by ygyg70** [tsedio/tsed-cli#375]
CLI version: 5.1.1
Project init options: 
? Choose the target Framework: Koa.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project Swagger, Testing, Linter
? Choose unit framework Vitest
? Choose linter tools framework EsLint
? Choose extra linter tools Prettier
? Choose the runtime: Node.js
? Choose the package manager: Yarn

Error msg:
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/processes.config.js` using `parserOptions.project`: ~/tsconfig.json

If I change eslint target to src folder, tests run correctly

**Comment by Romakita** [comment]
Hum the correct fix is to instrument eslint to run over all code excepted node_modules.
